FROM pytorch/pytorch:latest

RUN pip install torch
RUN pip install torchvision
RUN pip install tensorboard
RUN pip install transformers
RUN pip install numpy
RUN pip install sklearn
RUN pip install nltk

ENV PYTHONPATH /workspace

WORKDIR /workspace